USE pizzaria;

CREATE TABLE IF NOT EXISTS pizzas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    price FLOAT NOT NULL
);

INSERT INTO pizzas (name, description, price) VALUES
('Margherita', 'Pizza clássica com molho de tomate, mozzarella e manjericão.', 25.00),
('Pepperoni', 'Deliciosa pizza com pepperoni e queijo.', 30.00),
('Quattro Formaggi', 'Mistura de quatro queijos: mozzarella, gorgonzola, parmesão e ricota.', 35.00),
('Hawaiian', 'Pizza com presunto, abacaxi e queijo.', 28.00),
('Vegetariana', 'Pizza com legumes frescos e queijo.', 27.00),
('Calabresa', 'Pizza com calabresa, cebola e azeitonas.', 32.00),
('Portuguesa', 'Pizza com presunto, ovos, cebola e azeitonas.', 33.00),
('Frango com Catupiry', 'Pizza de frango desfiado com catupiry e azeitonas.', 34.00),
('Pepperoni Picante', 'Versão picante da pizza de pepperoni.', 31.00),
('Mexicana', 'Pizza com carne moída, jalapeños e queijo.', 29.00),
('Margherita Especial', 'Com azeitonas e orégano.', 26.00),
('Frango Barbecue', 'Frango com molho barbecue e cebolas.', 32.00),
('Pesto', 'Pizza com molho pesto e queijo de cabra.', 30.00),
('Funghi', 'Com cogumelos frescos e mozzarella.', 28.00),
('Lombo Canadense', 'Com lombo canadense e cebola.', 31.00),
('Alho e Óleo', 'Simples e saborosa com alho e azeite.', 22.00),
('Salame', 'Com salame picante e queijo.', 29.00),
('Cigano', 'Com carne de sol e cebola roxa.', 35.00),
('Bacon', 'Coberta com bacon crocante.', 34.00),
('Peito de Peru', 'Com peito de peru e queijo.', 33.00),
('Napolitana', 'Com molho de tomate fresco e mozzarella.', 27.00),
('Berinjela', 'Pizza de berinjela grelhada.', 28.00),
('Mariscos', 'Com frutos do mar e temperos.', 36.00),
('Tropicana', 'Com abacaxi, presunto e orégano.', 29.00),
('Spicy Chicken', 'Frango picante com pimenta.', 32.00),
('Provolone', 'Com queijo provolone e orégano.', 30.00),
('Cappicola', 'Com carne curada e queijo.', 31.00),
('Curry', 'Pizza de frango com molho curry.', 34.00),
('Pequena Delícia', 'Pizza mini com queijo e presunto.', 20.00),
('Floresta Negra', 'Com cogumelos e queijo provolone.', 28.00),
('Goiabada com Queijo', 'Pizza doce de goiabada com queijo.', 22.00),
('Vegetal', 'Com abobrinha e pimentões grelhados.', 27.00),
('Açai', 'Pizza com base de açai e frutas.', 35.00),
('Chester', 'Com peito de chester e cream cheese.', 32.00),
('Brócolis', 'Com brócolis e queijo cheddar.', 29.00),
('Burrata', 'Com burrata e tomate seco.', 30.00),
('Maracujá', 'Pizza com molho de maracujá.', 25.00),
('Roma', 'Com queijo feta e azeitonas.', 33.00),
('Caprese', 'Com tomate, mozzarella e manjericão.', 26.00),
('Carne Seca', 'Com carne seca e cebola roxa.', 34.00),
('Picanha', 'Pizza com fatias de picanha.', 36.00),
('Japonês', 'Com algas e atum.', 31.00),
('Pequena Veggie', 'Pizza vegetariana mini.', 22.00),
('Sardinha', 'Pizza de sardinha com cebola.', 28.00),
('Estilo Nova Iorque', 'Com borda recheada.', 35.00),
('Peito de Frango', 'Com peito de frango grelhado.', 30.00),
('Queijo Coalho', 'Com queijo coalho e mel.', 29.00),
('Bacon com Cheddar', 'Pizza com bacon e cheddar.', 32.00),
('Artesanal', 'Pizza feita artesanalmente com ingredientes frescos.', 28.00),
('Chili', 'Com carne moída e chili.', 34.00),
('Peito de Peru com Abacaxi', 'Com peito de peru e abacaxi.', 29.00),
('Sabor do Mar', 'Com camarão e alho.', 35.00),
('Cigano da Roça', 'Com carne de sol e queijo coalho.', 30.00),
('Bolonhesa', 'Com molho à bolonhesa.', 31.00),
('Mussarela de Búfala', 'Com mussarela de búfala e tomates.', 32.00),
('Gourmet', 'Pizza gourmet com ingredientes selecionados.', 36.00),
('Margarita Rústica', 'Com ingredientes rústicos e frescos.', 27.00),
('Nutella', 'Pizza doce com nutella.', 25.00),
('Bolo de Cenoura', 'Pizza doce de bolo de cenoura.', 22.00),
('Banana com Canela', 'Pizza doce de banana e canela.', 23.00),
('Doces', 'Pizza com vários doces variados.', 24.00),
('Romântica', 'Com morangos e chocolate.', 28.00),
('Salmão', 'Com salmão defumado.', 30.00),
('Parmesão', 'Com queijo parmesão e orégano.', 29.00),
('Ricota', 'Com ricota e espinafre.', 28.00),
('Trufa', 'Pizza com trufas e queijo.', 34.00),
('Shiitake', 'Com cogumelos shiitake e molho especial.', 35.00),
('Fajita', 'Com carne de frango e temperos mexicanos.', 33.00),
('Alfredo', 'Com molho alfredo e frango.', 30.00),
('Pequena Portuguesa', 'Pizza portuguesa mini.', 20.00),
('Ana', 'Com presunto e queijo.', 26.00),
('Vegan', 'Pizza vegana com tofu.', 29.00),
('Surf & Turf', 'Pizza com frutos do mar e carne.', 38.00),
('Misto Quente', 'Com presunto, queijo e orégano.', 30.00),
('Tomate Seco', 'Com tomate seco e rúcula.', 32.00),
('Salada', 'Pizza com salada em cima.', 27.00),
('Oriental', 'Com ingredientes orientais.', 29.00),
('Pomodoro', 'Com molho de tomate e manjericão.', 25.00),
('Estilo Chicago', 'Pizza profunda de estilo Chicago.', 40.00),
('Surfista', 'Com peixe e mariscos.', 36.00),
('Dez Queijos', 'Pizza com dez tipos de queijo.', 45.00),
('Cervejeira', 'Pizza com cerveja e bacon.', 31.00),
('Tomate', 'Com tomate fresco e ervas.', 28.00),
('Alho poró', 'Com alho poró e queijo.', 30.00),
('Burguer', 'Pizza com carne de hambúrguer.', 34.00),
('Laranja', 'Pizza doce de laranja.', 22.00),
('Trigo Sarraceno', 'Pizza sem glúten de trigo sarraceno.', 35.00),
('Básica', 'Pizza simples e deliciosa.', 24.00),
('Estilo Nova Iorque Especial', 'Pizza estilo Nova Iorque com borda recheada.', 38.00),
('Terra e Mar', 'Pizza com frutos do mar e carne.', 40.00),
('Delícia de Queijo', 'Com vários queijos.', 36.00),
('Sabor da Fazenda', 'Pizza com ingredientes frescos da fazenda.', 34.00),
('Pernil', 'Com pernil e queijo.', 32.00),
('Picante', 'Pizza picante com pimenta.', 31.00),
('Estilo Califórnia', 'Pizza com ingredientes frescos da Califórnia.', 37.00),
('Inverno', 'Com ingredientes de inverno.', 35.00),
('Açougue', 'Pizza com carne de açougue.', 36.00),
('Verão', 'Com ingredientes de verão.', 30.00),
('Dulce de Leche', 'Pizza doce com doce de leite.', 24.00),
('Cerveja com Queijo', 'Pizza com cerveja e queijo.', 28.00),
('Massinha', 'Pizza fina e crocante.', 26.00);
